<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-04T16:46:01 IST" name="Default suite" finished-at="2022-08-04T16:46:40 IST" duration-ms="38685">
    <groups>
    </groups>
    <test started-at="2022-08-04T16:46:01 IST" name="Default test" finished-at="2022-08-04T16:46:40 IST" duration-ms="38685">
      <class name="com.qa.TestLayer.TestCaseForLogin">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:01 IST" name="setup" finished-at="2022-08-04T16:46:06 IST" duration-ms="4712" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validUser_validPassword()[pri:1, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:06 IST" name="validUser_validPassword" finished-at="2022-08-04T16:46:13 IST" duration-ms="6811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUser_validPassword -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:13 IST" name="teardown" finished-at="2022-08-04T16:46:15 IST" duration-ms="2213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:15 IST" name="setup" finished-at="2022-08-04T16:46:16 IST" duration-ms="1384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validUser_InvalidPassword()[pri:2, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:16 IST" name="validUser_InvalidPassword" finished-at="2022-08-04T16:46:18 IST" duration-ms="1762" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.PageLayer.Login_swagLab.CheckTestCasestatus(Login_swagLab.java:40)
at com.qa.TestLayer.TestCaseForLogin.validUser_InvalidPassword(TestCaseForLogin.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUser_InvalidPassword -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:18 IST" name="teardown" finished-at="2022-08-04T16:46:21 IST" duration-ms="2195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:21 IST" name="setup" finished-at="2022-08-04T16:46:22 IST" duration-ms="1253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidUser_validPassword()[pri:3, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:22 IST" name="InvalidUser_validPassword" finished-at="2022-08-04T16:46:28 IST" duration-ms="6276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidUser_validPassword -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:28 IST" name="teardown" finished-at="2022-08-04T16:46:30 IST" duration-ms="2186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:30 IST" name="setup" finished-at="2022-08-04T16:46:31 IST" duration-ms="1208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidUser_InvalidPassword()[pri:4, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:31 IST" name="InvalidUser_InvalidPassword" finished-at="2022-08-04T16:46:38 IST" duration-ms="6273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidUser_InvalidPassword -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.qa.TestLayer.TestCaseForLogin@77847718]" started-at="2022-08-04T16:46:38 IST" name="teardown" finished-at="2022-08-04T16:46:40 IST" duration-ms="2203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.qa.TestLayer.TestCaseForLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
